config/routes.rb
Rails.application.routes.draw do

  resources :students, only: [:show, :new, :index, :create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'students#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

  validates :name, :email, :dob,  presence: true

  # emails must be unique
  validates :email, uniqueness: true

  # students name cannot be 'DROP TABLE' or 'ALTER TABLE'
  validates :name, exclusion: {in: ['DROP TABLE', 'ALTER TABLE']}

  # students must be eighteen years old
  validate :must_be_eighteen

  def must_be_eighteen
    if self.dob
      if self.dob > 18.years.ago
        self.errors.add(:dob, 'must be atleast 18 years ago')
      end
    end
  end
end

app/models/user.rb
require 'digest'

class User < ApplicationRecord

  has_secure_password 

  # def authenticate(password)
  #   # run the given pw thru the same encryption fn
  #
  #   # see if the pw_digest in our db is equal to the same thing
  #
  #   self.password_digest == Digest::SHA256.base64digest(password)
  #
  # end
  #
  #
  # def password=(password)
  #
  #   # encrypt the plaintext pw (by running it through a hash fn)
  #   hashed_pw = Digest::SHA256.base64digest(password)
  #   # put it into the database in a col called 'password_digest'
  #   self.password_digest = hashed_pw
  #
  # end

  # def screenname=(name)
  #   self.username = name
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  # memoization
  def current_user
    # if @current_user
    #   @current_user
    # else
    #   @current_user = User.find_by(id: session[:current_user_id])
    # end
    @current_user ||= User.find_by(id: session[:current_user_id])
  end

  def logged_in?
    !!current_user
  end

  def authorized?
    if !logged_in?
      flash[:message] = 'You must be logged in to view that content'
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:user][:username])

    if user && user.authenticate(params[:user][:password])
      session[:current_user_id] = user.id
      redirect_to students_path
    else
      flash[:message] = 'A user with that username could not be found in our records'
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    flash[:message] = 'Thanks for using our application!'
    redirect_to login_path

  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :authorized?, except: [:index]

  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    # if that student is valid

    if @student.valid?
      @student.save
      redirect_to @student
    # otherwise, re-render the form
    else
      render :new
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :dob)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>

  </head>
  <div class="ui blue inverted menu">
    <a href="/" class="item">
      <h1>Student Lister</h1>
    </a>
    <div class="right menu">
     <a class="item" href="<%= new_student_path %>">
       Create a New Student
     </a>
     <% if logged_in? %>
       <%= link_to 'Log Out', '/logout', method: 'delete', class: 'item' %>
    <% else %>
      <a class="item" href="/login">
        Log In
      </a>
    <% end %>
   </div>
  </div>
  <body>
    <div class="ui centered grid ">
      <div class="eight wide column">

        <%= yield %>

      </div>
    </div>
  </body>
</html>

app/views/students/index.html.erb
<h1>All Students</h1>
<% if current_user %>
  <h1>Welcome <%= current_user.username.capitalize %></h1>
<% end %>
<div class= 'ui huge middle aligned selection divided list'>
  <% @students.each do |student| %>
    <div class="item">
      <%= link_to student.name, student_path(student) %>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<h1>Create a Student!</h1>
<% if @student.errors.any? %>
  <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for(@student, {html: {class: 'ui form'}}) do |f| %>
  <div class='field'>
    <%= f.text_field :name, {placeholder: 'Enter the students name...', class: 'input field'} %>
  </div>
  <div class='field'>
    <%= f.text_field :email, placeholder: 'Enter the students email...' %>
  </div>
  <div class='field'>
    <%= f.date_field(:dob) %>
  </div>
  <div class='field'>
    <%= f.submit class: 'ui massive positive basic button' %>
  </div>
<% end %>

app/views/students/show.html.erb
<div class='ui raised segment'>
  <div class='ui fluid card'>
    <div class='huge content'>
      <div class='header'><h1><%= @student.name %></h1></div>
      <div class="meta">
         <span class="date">
           <h3><%= @student.dob.to_date %></h3>
         </span>
      </div>
      <div class="description">
        <h3><%= @student.email %></h3>
      </div>
    </div>
  </div>
</div>